fix(test/net): 在 afterEach 中 restore 被 SinonSpy 包上的方法
...而不是在各自测试代码的最后 restore，以避免一个测试失败，导致在未执
行到 restore 时就跳出，进而致使下一个使用 SinonSpy 监测同一方法的测试
失败：

  TypeError: Attempted to wrap get which is already wrapped